# Travis-CI configuration for Bioconductor packages
# https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

matrix:
  include:
  - os: linux
    r: bioc-release
  - os: osx
    r: bioc-release
  fast_finish: true

branches:
  only:
  - master

env:
  global:
    - LINTR_COMMENT_BOT=true

r_packages:
  - covr
bioc_packages:
  - BiocCheck
  - GenomeInfoDbData
  - S4Vectors
  - EnsDb.Hsapiens.v75
r_github_packages:
  - mjsteinbaugh/lintr

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - R CMD BiocCheck .

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: always
