# Travis-CI configuration for Bioconductor packages
# https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

r:
  - bioc-release
  - bioc-devel

# blocklist
branches:
  except:
  - develop

# External dependencies
# (required for zinbwave)
addons:
  apt:
    packages:
      - gsl-bin
      - libgsl-dev

env:
  global:
    - R_MAX_NUM_DLLS=150
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

# r_build_args: "--no-build-vignettes"
# r_check_args: "--no-vignettes"

# Set true before submission to Bioconductor
warnings_are_errors: true

# Temporarily enable to cache packages
script: true

notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
  - covr
bioc_packages:
  - BiocCheck

after_success:
  - Rscript -e 'covr::codecov()'
  - R CMD BiocCheck .
