language: general

services:
  - docker

branches:
  only:
    - master

before_install:
  - docker pull acidgenomics/singlecell
  - docker images
  # Prevent BiocCheck > checkCodingPractice > checkLogicalUseFiles error.
  - touch inst/rmarkdown/templates/quality-control/skeleton/_{footer,header,links}.Rmd

script:
  - docker run -ti --user="bioc" --volume="${PWD}:/bcbioSingleCell" --workdir="/bcbioSingleCell" acidgenomics/singlecell Rscript -e 'source("travis-docker.R")'

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
