language: r
cache: packages

matrix:
  include:
    - os: linux
      r: bioc-release
    - os: linux
      r: bioc-devel
    - os: osx
      r: bioc-release
  allow_failures:
    - os: osx
    - r: bioc-devel
  fast_finish: true

branches:
  only:
    - master

env:
  global:
    - LINTR_COMMENT_BOT=true

r_packages:
  - covr
bioc_packages:
  - BiocCheck
r_github_packages:
  - acidgenomics/lintr

after_success:
  - R CMD BiocCheck .
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
