# Travis-CI configuration for Bioconductor packages
# https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

matrix:
  include:
  - os: linux
    r: bioc-release
  - os: osx
    r: bioc-release

branches:
  only:
  - master

env:
  global:
    - LINTR_COMMENT_BOT=true

r_packages:
  - covr
bioc_packages:
  - BiocCheck
r_github_packages:
  - mjsteinbaugh/lintr

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - R CMD BiocCheck .

notifications:
  email:
    on_success: change
    on_failure: change
