# Travis-CI configuration for Bioconductor packages
# https://docs.travis-ci.com/user/languages/r

# Temporarily enable when caching package library.
# script: true

language: r
cache: packages
sudo: false
bioc_required: true

matrix:
  include:
  - os: osx
    r: bioc-release
    fortran: false
    latex: false
    warnings_are_errors: true
  - os: linux
    r: bioc-release
    warnings_are_errors: true
  # - os: linux
  #   r: bioc-devel
  #   latex: false
  #   warnings_are_errors: false
  fast_finish: true

env:
  global:
    - LINTR_COMMENT_BOT=true

r_packages:
  - covr
bioc_packages:
  - BiocCheck
  - GenomeInfoDbData
  - S4Vectors
  - EnsDb.Hsapiens.v75
r_github_packages:
  - jimhester/lintr

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - R CMD BiocCheck .

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: always
